version: '3'
services:
    api:
        container_name: reactphp_api
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
            - "9195:8080"
        volumes:
            - ./api:/app
    worker:
        container_name: reactphp_worker
        build:
            context: ./worker
            dockerfile: Dockerfile
        volumes:
            - ./worker:/app